import newyork from './images/offers-newyork.jpg'
import japan from './images/offers-japan.jpg'
import iran from './images/offers-iran.jpg'
import china from './images/offers-china.jpg'
import bangladesh from './images/offers-bangladesh.jpg'

export const offersLocations = [
    {
        id: 1,
        image: newyork,
        title: "Statue of Liberty.",
        place: "New York",
        rating: "4.8",
        days: 4,
        price: "450",
    },
    {
        id: 2,
        image: japan,
        title: "Osaka Castle",
        place: "Japan",
        rating: "4.7",
        days: 4,
        price: "700",
    },
    {
        id: 3,
        image: iran,
        title: "Dizin",
        place: "Iran",
        rating: "4.6",
        days: 5,
        price: "550",
    },
    {
        id: 4,
        image: china,
        title: "The Great Wall ",
        place: "China ",
        rating: "4.9",
        days: 7,
        price: "850",
    },
    {
        id: 5,
        image: bangladesh,
        title: "Sajek Valley",
        place: "Bangladesh",
        rating: "4.7",
        days: 3,
        price: "400",
    },
    {
        id: 6,
        image: china,
        title: "The Great Wall ",
        place: "China ",
        rating: "4.9",
        days: 7,
        price: "850",
    },
    {
        id: 7,
        image: newyork,
        title: "Statue of Liberty.",
        place: "New York",
        rating: "4.8",
        days: 4,
        price: "450",
    },
    {
        id: 8,
        image: japan,
        title: "Osaka Castle",
        place: "Japan",
        rating: "4.7",
        days: 4,
        price: "700",
    },
    {
        id: 9,
        image: iran,
        title: "Dizin",
        place: "Iran",
        rating: "4.6",
        days: 5,
        price: "550",
    },
    {
        id: 10,
        image: newyork,
        title: "Statue of Liberty.",
        place: "New York",
        rating: "4.8",
        days: 4,
        price: "450",
    },
    {
        id: 11,
        image: japan,
        title: "Osaka Castle",
        place: "Japan",
        rating: "4.7",
        days: 4,
        price: "700",
    },
    {
        id: 12,
        image: iran,
        title: "Dizin",
        place: "Iran",
        rating: "4.6",
        days: 5,
        price: "550",
    },
    {
        id: 13,
        image: china,
        title: "The Great Wall ",
        place: "China ",
        rating: "4.9",
        days: 7,
        price: "850",
    },
    {
        id: 14,
        image: bangladesh,
        title: "Sajek Valley",
        place: "Bangladesh",
        rating: "4.7",
        days: 3,
        price: "400",
    },
    {
        id: 15,
        image: china,
        title: "The Great Wall ",
        place: "China ",
        rating: "4.9",
        days: 7,
        price: "850",
    }
];